### ISSUE TITLE
Python package bids required in setup.py

### ISSUE THREAD

**Issue by josephmje** [raamana/visualqc#12]
* corticalqa version:
* Python version: 3.6.4
* Operating System: macOS 10.13.4

### Description

Running `visualqc_func_mri` on test data from OpenNeuro

### What I Did

```
visualqc_func_mri -b test
ModuleNotFoundError: No module named 'bids'
```

**Comment by raamana** [comment]
thanks Michael. I corrected it now, and this should be reflected in the next release (should happen pretty soon)

**Comment by raamana** [comment]
05bc7cb4fc2585e4864f3edf6a132fd762cc2e7b fixes #12

**Comment by raamana** [comment]
Hi Michael, Did you get a chance to install and try it?

**Comment by josephmje** [comment]
Hi Pradeep. Sorry I've haven't gotten around to trying it again but I'll do it this week. Thanks for the fix.

**Comment by raamana** [comment]
No worries, feel free to reopen this if you still have this problem.
