### ISSUE TITLE
Feature Request: Simple visualqc_t1_mri

### ISSUE THREAD

**Issue by cfhammill** [raamana/visualqc#14]
Maybe I'm just missing it, but it seems challenging to use `visualqc_t1_mri` with an arbitrary list of T1s. 

For example, I wanted to look at some bet segmentations I just ran and thought I'd try visualqc

```
visualqc_t1_mri \
  -i <(find -cmin -5000 | grep "anat\.nii" | cut -f 2 -d / | cut -f1 -d. | sed "s|_anat||") \
  --user_dir .
```
This fails saying my subject directories are empty (seems to think I want to use freesurfer outputs) alternatively, keeping the full path files

```
visualqc_t1_mri \
  -i <(find -cmin -5000 | grep "anat\.nii"") \
  --user_dir .
```

similarly fails.

It would be nice to have a simple mode where you pass a list of T1 files.

**Comment by cfhammill** [comment]
Thanks! ps I'll try to get you a few CIVET directories before the end of the week, I'll be gone the next two.

**Comment by raamana** [comment]
I am working on finishing new features to T1 mri tool, will try support the "folder of files" input files input spec soon.

The advantage of having a separate folder for each subject is we can dump visualizations of the data for future references, which is slightly more awkward with "list of files" (where you can create another folder of visualizations, with file names for correspondence).. Hence I prefer the former approach.

**Comment by raamana** [comment]
no worries on CIVET data, when you can

**Comment by cfhammill** [comment]
Do you always dump snapshots? And why can't the list of files version dump their snapshots to a common directory (e.g. cwd)?

**Comment by raamana** [comment]
No, I don't. This is a feature partially implemented, and planned to be common across all use cases, but not officially advertised.

we can always achieve it in various ways, just a matter of what works better, when considered as a whole.

**Comment by raamana** [comment]
Chris, this requires a bit more work than I imagined. I dont want to hurry this as I want to get the abstraction right.

For now, could you reformat the data (folders and symlinks) for now?

**Comment by cfhammill** [comment]
Sure, I can give that a shot.

**Comment by raamana** [comment]
pull the latest changes, it has additional features you might like.

**Comment by raamana** [comment]
you might need to reinstall from source

**Comment by raamana** [comment]
did it work, chris?

**Comment by cfhammill** [comment]
Haven't tried yet and am going on vacation for a couple weeks, will try when I get back.

**Comment by sjw42** [comment]
I'm also having a bit of trouble getting visualqc_t1_mri (which looks a fantastic tool) to work with my data and happened across this post. Would you be able to summarize what file structure is needed to run the command? I can't seem to get things right with setting up the data and pointing to -u and -m correctly. 
Thanks!
Steve

**Comment by raamana** [comment]
Hi Steve,

Go to the folder where you have the data and show me the listings? 

Essentially you need a separate folder (option for -u) for each ID (typically a subject) which should contain the file name specified by -m .. if you want only specific IDS, specify them in a file and pass it to —id_list

What was confusing to you? Clearly I need to improve the docs and options.

**Comment by sjw42** [comment]
That makes perfect sense and was what I took the instructions to mean. I was just having some difficulty getting things to work properly with the data in BIDS format (unique name for each participant's anatomical image). It worked fine when I created symlinks with a generic name to pass to the -m flag. Thanks for your help.

**Comment by raamana** [comment]
Very glad to hear you were able to use it. 

I didn't realize you were using BIDS format - I will be implementing support for it soon. If you had multiple sessions or acquisitions per subject, then BIDS is a great way to organize data? That's something I haven't come across yet, so didn't get to it yet, but BIDS will be supported in full.

Any other comments to improve it? Not sure which version you used, the latest one should help you with saturation and background extraction too..

Did the outlier detection flag help?

**Comment by raamana** [comment]
Hey guys! Let me know if you guys have any more issues.

**Comment by raamana** [comment]
closing this for now - please reopen if and when you attempt it again.
