### ISSUE TITLE
ValueError: Invalid fraction of outliers: must be more than 1/n (to enable detection of atleast 1)

### ISSUE THREAD

**Issue by soichih** [raamana/visualqc#33]
* visualqc version:
visualqc-0.4.1-py3-none-any

* Python version:
Python 3.6.9

* Operating System:
Ubuntu 18

### Description

When I try to launch visualqc_freesurfer I ran into the following error message.

```
hayashis@haswell:~/Downloads 1 visualqc_freesurfer --fs_dir fsdir
/home/hayashis/.local/lib/python3.6/site-packages/visualqc/utils.py:615: UserWarning: The following subjects do NOT have all the required files or some are empty - skipping them!
  'The following subjects do NOT have all the required files or some are empty - skipping them!')
visualqc


The following files do not exist or empty: 
 /home/hayashis/Downloads/fsdir/visualqc/mri/orig.mgz
/home/hayashis/Downloads/fsdir/visualqc/mri/aparc+aseg.mgz 


1 subjects are usable for review.
Traceback (most recent call last):
  File "/home/hayashis/.local/bin/visualqc_freesurfer", line 11, in <module>
    sys.exit(main())
  File "/home/hayashis/.local/lib/python3.6/site-packages/visualqc/__freesurfer__.py", line 11, in main
    freesurfer.cli_run()
  File "/home/hayashis/.local/lib/python3.6/site-packages/visualqc/freesurfer.py", line 1070, in cli_run
    wf = make_workflow_from_user_options()
  File "/home/hayashis/.local/lib/python3.6/site-packages/visualqc/freesurfer.py", line 1042, in make_workflow_from_user_options
    id_list, vis_type, source_of_features)
  File "/home/hayashis/.local/lib/python3.6/site-packages/visualqc/utils.py", line 783, in check_outlier_params
    raise ValueError('Invalid fraction of outliers: '
ValueError: Invalid fraction of outliers: must be more than 1/n (to enable detection of atleast 1)

```

### What I Did

```
visualqc_freesurfer --fs_dir fsdir

```

**Comment by raamana** [comment]
Hi,

As the error says:
```
The following files do not exist or empty: 
 /home/hayashis/Downloads/fsdir/visualqc/mri/orig.mgz
/home/hayashis/Downloads/fsdir/visualqc/mri/aparc+aseg.mgz 
```

the subject `visualqc` in this folder `/home/hayashis/Downloads/fsdir` does not have the `orig.mgz` and `aparc+aseg.mgz` files in a subfolder called `mri`..

what's the output of `ls -R /home/hayashis/Downloads/fsdir`

**Comment by raamana** [comment]
Also, use the `-old` flag to disable outlier detection for such small number of subjects

**Comment by soichih** [comment]
Thanks. Adding -old option cured it. I am visualizing only 1 subject at the moment. 

I also noticed this error message
```
Attempting to generate the surface visualizations of parcellation ...
Freesurfer does not seem to be installed - skipping surface visualizations.
```

Does this mean I visualqc requires freesurfer to work?

**Comment by raamana** [comment]
No - its a FYI warning message. Freesurfer is only required if you want to see the top row of surface visualizations also. They are generated using `tksurfer` (part of Freesurfer) for many reasons (familiarity, python's 3D libraries aren't great etc). It is not a full requirement -  it did work for you without surfaces, yes?

Please let me know if you have any other issues, or feedback. 

PS: Say hello to Franco and team at BrainLife! Glad to take suggestions from your team to improve these further.

**Comment by raamana** [comment]
Fixed this issue by disabling outlier detection with `n<10`. The new release 0.3.7.2 shouldn't have this problem.

Please feel free to open this or other issues if you have any other problems.

**Comment by raamana** [comment]
the latest release is actually 0.4.2.
