### ISSUE TITLE
visualqc_func_mri errors with the latest version of pybids

### ISSUE THREAD

**Issue by dokato** [raamana/visualqc#39]
* visualqc version: 0.4.3
* Python version: 3.76
* Operating System: CentOS

### What I Did

I tried to run

```
visualqc_func_mri -b SmallData/
```

 and got:

```
  File "/home/me/miniconda3/lib/python3.7/site-packages/visualqc/functional_mri.py", line 344, in init_getters
    from bids.layers import BIDSLayout
ModuleNotFoundError: No module named 'bids.grabbids'
```

I noticed that in the version `0.7.0` from Jan 2019 they changed this `grabbids` submodule to `layout`:
 https://github.com/bids-standard/pybids/blob/master/CHANGELOG.md#version-070-january-10-2019

Unfortunately, the fix wasn't as easy as replacing import in 344 of `functional_mri.py`:

```python
from bids.layout import BIDSLayout
```

After doing that I got instead

```
 File "/home/me/miniconda3/lib/python3.7/site-packages/bids/layout/layout.py", line 969, in get
    raise ValueError(msg + "If you're sure you want to impose "
ValueError: 'extensions' is not a recognized entity. Did you mean ['extension']? If you're sure you want to impose this constraint, set invalid_filters='allow'.
```

Maybe temporary fix would be to specify `pybids` version in requirements?

**Comment by raamana** [comment]
thanks @dokato for the report. Let me look in quickly and advise you shortly

**Comment by raamana** [comment]
could you uninstall and reinstall, and try the latest 0.4.7 version? Thanks.

**Comment by dokato** [comment]
Thanks for a quick reaction 👍 This solves the import problem.
