### ISSUE TITLE
ValueError: Supplied images do not match

### ISSUE THREAD

**Issue by dlevitas** [raamana/visualqc#43]
* visualqc version: 0.4.8
* Python version: 3.6.8
* Operating System: Red Hat Linux

### Description
This is related to #31, where I'm getting the following error:
```
ValueError: Supplied images do match in size. This image has dimensions: (208, 106, 128) They must all have: [208 120 128]
```
I used nibabel to ensure that the original and defaced images contain the same shape & dimensions, so I'm unsure how to work around this issue. 

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
visualqc_defacing --user_dir /N/slate/dlevitas/dan_test/sub-OpenSciJan22/anat/defaced_test --defaced_name defaced.nii.gz --mri_name orig.nii.gz --render_name rendered.png -o $PWD/visualqc --id_list /N/slate/dlevitas/dan_test/sub-OpenSciJan22/anat/defaced_test/subject_ids.txt
```

**Comment by raamana** [comment]
Thanks @dlevitas for reporting this. Let me look into what I did to fix this for #31 and get back to you shortly. I am guessing you read through #31 and did all that is suggested it ensure there are no issues on your end?

**Comment by dlevitas** [comment]
Correct, as far as I can tell. Both my images have dimensions of ```[208 120 128]```, so I'm unsure why it claims one of my images has dimensions of ```(208, 106, 128)```

**Comment by raamana** [comment]
thanks! Is it possible to share those images for me to run some debugging? its totally fine if you can't as I understand there are many issues with with that. The check I am running is shown below -- which works for some defacers and not others (as noted in #31).. It may also be due to me cropping them to their extents individually, which can create differing sizes! Let me double check.

```python
np.isclose(np.squeeze(img_one.shape), np.squeeze(img_two.shape)).all()
```

**Comment by raamana** [comment]
or point me to some openly available datasets. I will check in BIDSonym

**Comment by dlevitas** [comment]
For this data, I can share it. Is there a Dropbox account I can send it to?

**Comment by raamana** [comment]
can you send a non-google-drive link (dropbox is fine) that can be downloaded without logging in to my raamanap AT pitt . edu ? Thanks.

**Comment by raamana** [comment]
ideally for the subject / algorithm that caused this error :)

**Comment by raamana** [comment]
Thanks for sending the link. I can NOT open google drive at work (IT policy), so I will test the bugfix I just wrote when I get home.

**Comment by raamana** [comment]
hi Dan, I just released a new version with a bug fix. Can you try the new version with:

```bash
pip uninstall visualqc
pip install -U visualqc --no-cache-dir
```

**Comment by dlevitas** [comment]
Re-installed and everything seems to work now, thanks!
