### ISSUE TITLE
issue on using -g flag to specifies the name of segmentation image, such as aseg.mgz

### ISSUE THREAD

**Issue by XinQi7788** [raamana/visualqc#49]
* visualqc version: 
* Python version: 3.6 ---   (here I use the conda activate python=3.6 to setup its python environment)
* Operating System: Linux

### Description
I would like to only visualize segmentation images (volumetric) of aseg.mgz to be overlaid on the MRI. 

### What I Did
Within the conda activated visualqc enviroment

There is no issue to run the command as **visualqc_freesurfer -i listImageID.txt -f . -o .** 
Because I only want to visualize subcortical segmentations, so I add a flag as below
**visualqc_freesurfer -i listImageID.txt -f . -o .  -g aseg.mgz** 

But got error saying that "segmentation image for ADNI-xxx-T1w-001 does not contain requested label set!" . 

The aseg.mgz is inside the same mri folder as the aparc+aseg.mgz. 

Please help me on this issue. Looking forward to your reply. Thank you so much.
Xin

**Comment by raamana** [comment]
Hi Xin, thanks for the report. Could you try specifying the `--vis_type labels_volumetric ` and specifically choose which segmentations you want to visualize e.g. if you want to focus on thalamus alone `--labels 10 49`

so something like: 
`visualqc_freesurfer -i listImageID.txt -f . -o . -g aseg.mgz --vis_type labels_volumetric --labels 10 49`

**Comment by raamana** [comment]
btw labels are from the [Freesurfer Lookup table](https://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/AnatomicalROI/FreeSurferColorLUT)

**Comment by raamana** [comment]
you can try without specifying label set first, and it should work so long as you choose the right vis type. If not, let me know so I can fix the bug.

**Comment by raamana** [comment]
Actually vis_type labels_volumetric is not very useful, so I encourage `-v labels_contour` :)

**Comment by XinQi7788** [comment]
Thanks for quick reply! 

I am testing the -v labels_coutours --labels 17 53 (for hippocampus) now... seems working now :). 

BTW, another error related to Outlier detection shows as below.

Traceback (most recent call last):
  File "/home/Xin/miniconda3/envs/visualqcenv/lib/python3.6/site-packages/visualqc-0.5+1.g8e386c1-py3.6.egg/visualqc/workflows.py", line 405, in detect_outliers
    raise IOError('Unable to read/assemble features for outlier '
OSError: Unable to read/assemble features for outlier detection. Skipping them!

Thank you very much.
Xin

**Comment by raamana** [comment]
Great to hear that. Regarding the outlier detection error, are you using the 0.5 version from pypi directly, or is that something you installed in developer mode locally (as the version tag visualqc-0.5+1.g8e386c1 implies)? We recently changed the OLD behaviour not to throw an error by default

**Comment by XinQi7788** [comment]
> you can try without specifying label set first, and it should work so long as you choose the right vis type. If not, let me know so I can fix the bug.

**It seems it needs specify the label along with vis_type.**  If without specifying the label, the error shows as below:

Traceback (most recent call last):
  File "/home/Xin/miniconda3/envs/visualqcenv/bin/visualqc_freesurfer", line 33, in <module>
    sys.exit(load_entry_point('visualqc==0.5+1.g8e386c1', 'console_scripts', 'visualqc_freesurfer')())
  File "/home/Xin/miniconda3/envs/visualqcenv/lib/python3.6/site-packages/visualqc-0.5+1.g8e386c1-py3.6.egg/visualqc/__freesurfer__.py", line 11, in main
    freesurfer.cli_run()
  File "/home/Xin/miniconda3/envs/visualqcenv/lib/python3.6/site-packages/visualqc-0.5+1.g8e386c1-py3.6.egg/visualqc/freesurfer.py", line 1070, in cli_run
    wf = make_workflow_from_user_options()
  File "/home/Xin/miniconda3/envs/visualqcenv/lib/python3.6/site-packages/visualqc-0.5+1.g8e386c1-py3.6.egg/visualqc/freesurfer.py", line 1018, in make_workflow_from_user_options
    vis_type, label_set = check_labels(user_args.vis_type, user_args.label_set)
  File "/home/Xin/miniconda3/envs/visualqcenv/lib/python3.6/site-packages/visualqc-0.5+1.g8e386c1-py3.6.egg/visualqc/utils.py", line 919, in check_labels
    ''.format(cfg.label_types))
ValueError: When vis_type is one of ('labels_volumetric', 'labels_contour'), at least one label must be specified!

**Comment by XinQi7788** [comment]
> Great to hear that. Regarding the outlier detection error, are you using the 0.5 version from pypi directly, or is that something you installed in developer mode locally (as the version tag visualqc-0.5+1.g8e386c1 implies)? We recently changed the OLD behaviour not to throw an error by default

Here is what I did to download and install the visualqc on my AWS EC2.
1). setup a conda enviroment for visualqc by specify python=3.6 (as suggested in our previous communication)
2). download visualqc from sources , then go inside the visualqc folder, then python setup.py install 
git clone git://github.com/raamana/visualqc
cd visualqc
python setup.py install

How do I know the version of visuaqc I installed? Shall I re git clone its repo? Thank you very much.

Xin

**Comment by XinQi7788** [comment]
Another question is how to 

> Great to hear that. Regarding the outlier detection error, are you using the 0.5 version from pypi directly, or is that something you installed in developer mode locally (as the version tag visualqc-0.5+1.g8e386c1 implies)? We recently changed the OLD behaviour not to throw an error by default

**Comment by XinQi7788** [comment]
> > you can try without specifying label set first, and it should work so long as you choose the right vis type. If not, let me know so I can fix the bug.
> 
> **It seems it needs specify the label along with vis_type.** If without specifying the label, the error shows as below:
> 
> Traceback (most recent call last):
> File "/home/Xin/miniconda3/envs/visualqcenv/bin/visualqc_freesurfer", line 33, in
> sys.exit(load_entry_point('visualqc==0.5+1.g8e386c1', 'console_scripts', 'visualqc_freesurfer')())
> File "/home/Xin/miniconda3/envs/visualqcenv/lib/python3.6/site-packages/visualqc-0.5+1.g8e386c1-py3.6.egg/visualqc/**freesurfer**.py", line 11, in main
> freesurfer.cli_run()
> File "/home/Xin/miniconda3/envs/visualqcenv/lib/python3.6/site-packages/visualqc-0.5+1.g8e386c1-py3.6.egg/visualqc/freesurfer.py", line 1070, in cli_run
> wf = make_workflow_from_user_options()
> File "/home/Xin/miniconda3/envs/visualqcenv/lib/python3.6/site-packages/visualqc-0.5+1.g8e386c1-py3.6.egg/visualqc/freesurfer.py", line 1018, in make_workflow_from_user_options
> vis_type, label_set = check_labels(user_args.vis_type, user_args.label_set)
> File "/home/Xin/miniconda3/envs/visualqcenv/lib/python3.6/site-packages/visualqc-0.5+1.g8e386c1-py3.6.egg/visualqc/utils.py", line 919, in check_labels
> ''.format(cfg.label_types))
> ValueError: When vis_type is one of ('labels_volumetric', 'labels_contour'), at least one label must be specified!

Sorry, I accidently close the question. I still want to know the answers :). Thanks a lot

**Comment by raamana** [comment]
Thanks Xi, appreciate the detailed responses. If you have direct access to pypi, the recommended installation method is 
`pip install -U visualqc`. Is that not possible for you?

regarding the need to specify specific labels, i can't recall the exact rationale back then, but I think it's more useful as a QC tool with only few selected (you can zoom in closer etc) than showing everything present in the aseg. Moreover that allows for reporting errors e.g. when it encounters subjects without the requested labels. Does that make sense?

any other feedback or suggestions for improvements?

**Comment by XinQi7788** [comment]
> Thanks Xi, appreciate the detailed responses. If you have direct access to pypi, the recommended installation method is
> `pip install -U visualqc`. Is that not possible for you?
> 
> regarding the need to specify specific labels, i can't recall the exact rationale back then, but I think it's more useful as a QC tool with only few selected (you can zoom in closer etc) than showing everything present in the aseg. Moreover that allows for reporting errors e.g. when it encounters subjects without the requested labels. Does that make sense?
> 
> any other feedback or suggestions for improvements?

Thank, Predeep for so quick reply. Yes, _pip install -U visualqc_ works well.

I did send you another email directly because it is easily to attach a picture in email instead of in github. :). Thanks a lot!
