### ISSUE TITLE
Attempting to generate the surface visualizations of parcellation ... Freesurfer does not seem to be installed - skipping surface visualizations.

### ISSUE THREAD

**Issue by MarcKhoury8** [raamana/visualqc#53]
* visualqc version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by raamana** [comment]
Hi @MarcKhoury8, thanks for reporting the issue. As the error message suggests, you need Freesurfer, specifically tksurfer, installed, so visualqc can generate the necessary 3D surface visualizations. Do you have a question for any specific help?

**Comment by MarcKhoury8** [comment]
Hi @raamana, thank you for the reply. I've dug a bit into this tksurfer component and it seems as thought it has be deprecated and replaced with "freeview". I have freeview installed and it has also been sourced. My question is if there is a way to get around this issue and visualize the surface outputs? Specifically, if tksurfer is not deprecated or if freeview is now the replacement, are you aware what the process is to utilize either?
