### ISSUE TITLE
Surface Visualization issue

### ISSUE THREAD

**Issue by MarcKhoury8** [raamana/visualqc#54]
Hello Raamana, 

Currently trying to use the visualQC output for surfaces visualizations. They work for aparc+aseg/
I have freesurfer installed and sourced to terminal, however, this message keeps popping up:

Attempting to generate the surface visualizations of parcellation ...
Freesurfer does not seem to be installed - skipping surface visualizations.

Not sure if this is an issue with running it in terminal or if there's a separate installation procedure needed for visualqc.

**Comment by raamana** [comment]
Can you give me more details? esp. the output logs on the terminals, with the full traceback, and what datasets you've been using? 

can you run this command and give me the output:
```bash
echo $FREESURFER_HOME
which tksurfer
```

if FREESURFER_HOME is not setup correctly, or it can't find tksurfer in its path, visualqc can't generate the surface visualizations, as it depends on them. Check Freesurfer installation instructions to double check it was done properly.

**Comment by raamana** [comment]
Thanks Marc, I didn't realize tksurfer has been deprecated. Let me check on Freesurfer's website, and get back to you shortly on using freeview instead of tksurfer

**Comment by raamana** [comment]
regarding the other `KeyError: 'SUB001412_1-1-1954455-1 copy'`, please reinstall the latest version and I think the latest version fixes this bug:

```bash
pip uninstall visualqc
pip install -U visualqc --no-cache-dir
```

**Comment by MarcKhoury8** [comment]
Hi Raamana, 

Thank you for the reply and help on this, much appreciated. I've gone ahead and applied those changes. I do want to mention that I admire the work done with visualQC and Neuropredict, I look forward to any future projects of yours! Thanks, will keep an eye out for your response.

**Comment by raamana** [comment]
Thanks Marc, glad to hear that. yes, I am happy to collaborate and extend them working with you as needed.

**Comment by raamana** [comment]
Also, would you be interested in helping adopt `freeview` or `tksurferfv` (notice the suffix `fv` to tksurfer) for this part of VisualQC? If you can't, it's absolutely fine, but I see that you forked it, so I just wanted to avoid us both doing the same thing :)

**Comment by MarcKhoury8** [comment]
Thanks @raamana, I am fairly new to Github and accidentally forked the page. However, I am more than open helping in any way that I can. Would this be for the purpose of this specific issue or for future work on VisualQC?

**Comment by raamana** [comment]
I was thinking of this specific issue to start with, if your time and skills allow it. And we are always open to contributions in the future. Let me know if you want to this take up, then I can walk you through how to get it done rather quickly.

**Comment by MarcKhoury8** [comment]
I am a bit new to this territory but if you could walk me that'd be great. Let me know how you would like to proceed and what you think he best approach is.  Definitely open to future collaborations as well.

**Comment by raamana** [comment]
How about a zoom call tomorrow or day after? I am available in the afternoon times 2-4pm. Let me know your email. Mine is raamanap@pitt.edu

**Comment by MarcKhoury8** [comment]
That works great for me, will send you a zoom invite for 3pm! Thanks raamana, looking forward to it. My email is marc.khoury.397@gmail.com

**Comment by MarcKhoury8** [comment]
**For tomorrow

**Comment by raamana** [comment]
closing it as #57 fixes this
