### ISSUE TITLE
For every second image in defacing interface pressing 'p' or clicking 'Pass' checkbox does not record the rating

### ISSUE THREAD

**Issue by Arshitha** [raamana/visualqc#75]
* visualqc version: 0.6.6
* Python version: 3.11.3
* Operating System: Linux

### Description

Describe what you were trying to get done. 
I'm trying to rate a bunch of defaced images for accuracy.

Tell us what happened, what went wrong, and what you expected to happen.
For every second image, pressing 'p' or clicking 'Pass' checkbox gives the "You have not rated the current subject! Please rate it before you can advance to next subject, or to quit.." message. Only when I **uncheck** the pass rating it moves on to the next image. Here's the standard output. 

```
Reviewing sub-24236/acq-original/T1w
You have not rated the current subject! Please rate it before you can advance to next subject, or to quit..
    id: sub-24236/acq-original/T1w
rating: ['Pass']
 notes: None

Reviewing sub-24139/acq-original/T1w
    id: sub-24139/acq-original/T1w
rating: ['Pass']
 notes: None

Reviewing sub-23601/acq-original/T1w
You have not rated the current subject! Please rate it before you can advance to next subject, or to quit..
You have not rated the current subject! Please rate it before you can advance to next subject, or to quit..
    id: sub-23601/acq-original/T1w
rating: ['Pass']
 notes: None

Reviewing sub-24260/acq-original/T1w
    id: sub-24260/acq-original/T1w
rating: ['Pass']
 notes: None

Reviewing sub-23069/acq-original/T1w
You have not rated the current subject! Please rate it before you can advance to next subject, or to quit..
You have not rated the current subject! Please rate it before you can advance to next subject, or to quit..
    id: sub-23069/acq-original/T1w
rating: ['Pass']
 notes: None

```

### What I Did

I'm not sure how to go about fixing this issue. So I have not tried potential solutions other than re-installing v0.6.2 of visualqc which gave me a different set of errors that were mostly related to dependency conflicts within the environment.

Here's the command I ran which opened up the rating interface successfully but the issue was with the rating itself.
```
vqcdeface -u defacing_outputs_demo/defacing_QC -i defacing_outputs_demo/defacing_QC/defacing_id_list.txt -m orig.nii.gz -d defaced.nii.gz -r defaced_render
```

**Comment by raamana** [comment]
Thanks for the report Arshitha! That’s so weird as I don’t recall touching that part of the code recently. Let me take a look and get back to you.

**Comment by Arshitha** [comment]
Thanks @raamana , please let me know if I can help out by testing anything on my end!

**Comment by Arshitha** [comment]
No worries, @raamana , thank you for the update!

**Comment by raamana** [comment]
Can you copy paste the version info of matplotlib and other libraries output by VisualQC at the start of output log? I think this is due to deprecated changes in matplotlib and I need to ensure my new implementation would work across all MPL versions

**Comment by raamana** [comment]
the issue seems to be with the [deprecations](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.7.0.html#checkbuttons-rectangles-and-checkbuttons-lines) in the latest matplotlib version `3.7.0`. I suggest to use older versions for now for a quick fix (with commands below), and I will find a way to make it work on all versions.

```
pip uninstall matplotlib
pip install matplotlib==3.6.1 --no-cache-dir
```

**Comment by Arshitha** [comment]
@raamana Thank you for the update. I'll be using vqcdeface this afternoon so I'll try the fix you suggested and report back!

**Comment by Arshitha** [comment]
@raamana Just confirming that switching to matplotlib 3.6.1 worked and I didn't see the issue anymore.

**Comment by raamana** [comment]
great, glad to hear that!

**Comment by ericearl** [comment]
I'm having the same problem with VisualQC v0.6.6 and I've tried both of matplotlib versions 3.7.2 and 3.8.3...

**Comment by ericearl** [comment]
Aaaaaaaaaaannnnnnddd, now I read the one post you made above... and it's working again!

```shell
pip uninstall matplotlib
pip install matplotlib==3.6.1 --no-cache-dir
```
Sorry!

**Comment by raamana** [comment]
no worries at all Eric! Glad its working for you.

I haven't found the time to work on this yet, but will try to look into this again and implement a new version that would work with all versions
