### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by Xjiale** [raamana/visualqc#76]
* visualqc version: visualqc 0.6.6
* Python version:3.8.10
* Operating System:platform Linux-5.15.0-78-generic-x86_64-with-glibc2.29 #85~20.04.1-Ubuntu SMP Mon Jul 17 09:42:39 UTC 2023

### Description

visualqc_freesurfer

Tell us what happened, what went wrong, and what you expected to happen.
I would like to use visualqc_freesurfer to check the results of Freesurfer. My Freesurfer output result path is /home/u/DP/Project, and my Freesurfer's environment variable is set to FREESURFER_HOME=/usr/local/freesurfer/7.3.2. I have installed visualqc in the terminal, but when I try to run sudo visualqc_freesurfer --fs_dir /home/u/DP/FreeSurfer60 --id_list /home/u/DP/FreeSurfer60/list_complete.txt, I get an error: 'the environment variable FREESURFER_HOME is not set! Freesurfer does not seem to be installed - skipping surface visualizations
Describe what you were trying to get done.

I would like to know how to solve my problem

### What I Did

Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.

<pre>

<font color="#4E9A06"><b>u@u</b></font>:<font color="#3465A4"><b>~</b></font> $ sudo visualqc_freesurfer --fs_dir /home/u/DP/FreeSurfer60 --id_list /home/u/DP/FreeSurfer60/list_complete.txt

Freesurfer QC module
Time stamp : 2023-08-02 09:38:13

version info: visualqc 0.6.6
numpy 1.24.4 / scipy 1.10.1 / matplotlib 3.7.2
python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0]
platform Linux-5.15.0-78-generic-x86_64-with-glibc2.29
#85~20.04.1-Ubuntu SMP Mon Jul 17 09:42:39 UTC 2023

109 subjects are usable for review.
Input folder: /home/u/DP/FreeSurfer60
Output folder: /home/u/DP/FreeSurfer60/visualqc
Preprocessing data - please wait .. 
	(or contemplate the vastness of universe! )
Extracting feature type: cortical
Extracting feature type: subcortical
Extracting feature type: both
Extracting feature type: whole_brain

Running outlier detection based on cortical measures:

Possible outliers (22 / 109):
C0016
C0021
C0027
C0035
C0036
M0007
M0010
M0015
M0018
M0019
M0022
M0035
M0042
M0046
M0051
M0052
M0060
M0061
M0070
M0080
M0086
M0087

Running outlier detection based on subcortical measures:

Possible outliers (22 / 109):
C0003
C0016
M0005
M0010
M0019
M0020
M0023
M0024
M0025
M0031
M0035
M0049
M0050
M0052
M0054
M0060
M0065
M0068
M0070
M0077
M0080
M0085

Running outlier detection based on both measures:

Possible outliers (22 / 109):
C0015
C0035
C0036
M0002
M0007
M0010
M0019
M0022
M0025
M0035
M0042
M0046
M0051
M0052
M0060
M0061
M0064
M0067
M0070
M0072
M0080
M0086

Running outlier detection based on whole_brain measures:

Possible outliers (22 / 109):
C0015
C0035
C0036
M0002
M0007
M0010
M0019
M0022
M0025
M0035
M0042
M0046
M0051
M0052
M0060
M0061
M0064
M0067
M0070
M0072
M0080
M0086

Attempting to generate surface visualizations of parcellation ...
the environment variable FREESURFER_HOME is not set!
Freesurfer does not seem to be installed - skipping surface visualizations.
Processing C0003
Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.8/dist-packages/visualqc/freesurfer.py&quot;, line 750, in make_vis_pial_surface
    all_vis_exist = all([vp.exists() for vp in vis_files.values()])
UnboundLocalError: local variable &apos;vis_files&apos; referenced before assignment
unable to generate 3D surf vis for lh hemi - skipping
Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.8/dist-packages/visualqc/freesurfer.py&quot;, line 750, in make_vis_pial_surface
    all_vis_exist = all([vp.exists() for vp in vis_files.values()])
UnboundLocalError: local variable &apos;vis_files&apos; referenced before assignment
unable to generate 3D surf vis for rh hemi - skipping
Traceback (most recent call last):
  File &quot;/usr/local/bin/visualqc_freesurfer&quot;, line 8, in &lt;module&gt;
    sys.exit(main())
  File &quot;/usr/local/lib/python3.8/dist-packages/visualqc/__freesurfer__.py&quot;, line 12, in main
    freesurfer.cli_run()
  File &quot;/usr/local/lib/python3.8/dist-packages/visualqc/freesurfer.py&quot;, line 1193, in cli_run
    wf.run()
  File &quot;/usr/local/lib/python3.8/dist-packages/visualqc/workflows.py&quot;, line 95, in run
    self.preprocess()
  File &quot;/usr/local/lib/python3.8/dist-packages/visualqc/freesurfer.py&quot;, line 347, in preprocess
    self.generate_surface_vis()
  File &quot;/usr/local/lib/python3.8/dist-packages/visualqc/freesurfer.py&quot;, line 363, in generate_surface_vis
    make_vis_pial_surface(self.in_dir, sid, self.out_dir,
  File &quot;/usr/local/lib/python3.8/dist-packages/visualqc/freesurfer.py&quot;, line 766, in make_vis_pial_surface
    for hemi_l, view in cfg.view_pref_order[vis_tool]:
KeyError: None

</pre>

**Comment by Xjiale** [comment]
Dear Raamana:
       
         According to your advice, I ran the following code:


-------- freesurfer-linux-ubuntu20_x86_64-7.3.2-20220804-6354275 --------
Setting up environment for FreeSurfer/FS-FAST (and FSL)
FREESURFER_HOME   /usr/local/freesurfer/7.3.2
FSFAST_HOME       /usr/local/freesurfer/7.3.2/fsfast
FSF_OUTPUT_FORMAT nii.gz
SUBJECTS_DIR      /usr/local/freesurfer/7.3.2/subjects
MNI_DIR           /usr/local/freesurfer/7.3.2/mni
***@***.***:~$ export FREESURFER_HOME="/usr/local/freesurfer/7.3.2"
***@***.***:~$ visualqc_freesurfer --fs_dir /home/u/DP/FreeSurfer60 --id_list /home/u/DP/FreeSurfer60/list_complete.txt


Freesurfer QC module
Time stamp : 2023-08-03 13:16:13


version info: visualqc 0.6.6
numpy 1.24.4 / scipy 1.10.1 / matplotlib 3.7.2
python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0]
platform Linux-5.15.0-78-generic-x86_64-with-glibc2.29
#85~20.04.1-Ubuntu SMP Mon Jul 17 09:42:39 UTC 2023




Traceback (most recent call last):
  File "/usr/local/bin/visualqc_freesurfer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/visualqc/__freesurfer__.py", line 12, in main
    freesurfer.cli_run()
  File "/usr/local/lib/python3.8/dist-packages/visualqc/freesurfer.py", line 1188, in cli_run
    wf = make_workflow_from_user_options()
  File "/usr/local/lib/python3.8/dist-packages/visualqc/freesurfer.py", line 1130, in make_workflow_from_user_options
    in_dir, source_of_features = check_input_dir(user_args.fs_dir, None, vis_type,
  File "/usr/local/lib/python3.8/dist-packages/visualqc/utils.py", line 601, in check_input_dir
    raise IOError('Freesurfer directory specified does not exist!')
OSError: Freesurfer directory specified does not exist!


   I encountered an error: Freesurfer directory specified does not exist! Could you please tell me if I have done something wrong? Thank you very much.


  



From: Pradeep Reddy Raamana ***@***.***>
Date: 2023-08-02 21:08:14
To: raamana/visualqc ***@***.***>
Cc: Xjiale ***@***.***>,Author ***@***.***>
Subject: Re: [raamana/visualqc] help wanted (Issue #76)

Hi, thanks for reporting the bug. It appears to be an issue with your environment - I noticed you are running the command with sudo. was that necessary? if not, can you try it without sudo? if that doesn't work, get help with your local system/IT admin to ensure you have the environment variable FREESURFER_HOME set before running command.
another hacky way to do it would be to prefix the visualqc command with the variable set command like:
export FREESURFER_HOME="/usr/local/freesurfer/7.3.2"; visualqc_freesurfer --fs_dir /home/u/DP/FreeSurfer60 --id_list /home/u/DP/FreeSurfer60/list_complete.txt
which should work i think. Keep me posted.

**Comment by raamana** [comment]
it appears the directory you mentioned for FREESURFER_HOME does not exist, which I assumed it was. This is a simple issue, and you might need someone to walk you through this. Did you try talk to some of your lab mates, your PI, or IT admins? if you don't have anyone to help locally, we can try to schedule a zoom session and work it out together.

**Comment by Xjiale** [comment]
Dear Raamana:
         Thank you very much for your help! "You are right". I have worked out the problem with my lab colleagues. Thank you again for your help!









发件人：Pradeep Reddy Raamana ***@***.***>
发送日期：2023-08-03 21:25:07
收件人：raamana/visualqc ***@***.***>
抄送人：Xjiale ***@***.***>,Author ***@***.***>
主题：Re: [raamana/visualqc] help wanted (Issue #76)

it appears the directory you mentioned for FREESURFER_HOME does not exist, which I assumed it was. This is a simple issue, and you might need someone to walk you through this. Did you try talk to some of your lab mates, your PI, or IT admins? if you don't have anyone to help locally, we can try to schedule a zoom session and work it out together.

**Comment by raamana** [comment]
so glad to hear it worked out - please feel free open an another issues if you run into any issues.
